name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        uses: oven-sh/setup-bun@v1
      - run: bun install

      - name: Test
        run: |
          bun run type
          bun run lint
          bun run prettier.check
          bun run build
          bun run test
          bun run test:register
          bun run size

      - name: Build example
        run: cd example && bun install && bun run build
