name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Type Check
        run: bun run type

      - name: Lint
        run: bun run lint

      - name: Prettier Check
        run: bun run prettier.check

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test

      - name: Test Register
        run: bun run test:register

      - name: Size Check
        run: bun run size

      - name: Build example
        run: cd example && bun install && bun run build
